# Generated by Django 5.2.5 on 2025-09-02 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automacao',
            options={'ordering': ['-started_at'], 'verbose_name': 'Automação', 'verbose_name_plural': 'Automações'},
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='automacao',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automacao',
            name='erros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automacao',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automacao',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automacao',
            name='projeto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='automacao',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automacao',
            name='sucesso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='automacao',
            name='tipo',
            field=models.CharField(default='sync_sheet', max_length=50),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('execucao', 'Em execução'), ('concluida', 'Concluída'), ('falhou', 'Falhou'), ('pausada', 'Pausada')], default='pendente', max_length=20),
        ),
    ]
