# Generated by Django 5.2.5 on 2025-09-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0002_alter_automacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automacao',
            options={'ordering': ('-started_at',)},
        ),
        migrations.AlterField(
            model_name='automacao',
            name='erros',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='mensagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='projeto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('falhou', 'Falhou'), ('pausada', 'Pausada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='sucesso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='tipo',
            field=models.CharField(choices=[('sync_sheet', 'sync_sheet')], max_length=32),
        ),
    ]
