# Generated by Django 5.2.5 on 2025-09-08 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0003_alter_automacao_options_alter_automacao_erros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregavelLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregavel', models.CharField(max_length=200, unique=True)),
                ('itens_do_entregavel', models.PositiveIntegerField(blank=True, null=True)),
                ('percentual_do_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valor_do_orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entregável',
                'verbose_name_plural': 'Entregáveis',
            },
        ),
        migrations.CreateModel(
            name='ProjetoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=200, unique=True)),
                ('receita_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('prazo_de_vencimento', models.DateField(blank=True, null=True)),
                ('total_de_aulas', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados do Projeto',
                'verbose_name_plural': 'Dados do Projeto',
            },
        ),
        migrations.CreateModel(
            name='EdicaoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, default='', max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('cortes_disponiveis', models.PositiveIntegerField(blank=True, null=True)),
                ('roteiros_feitos', models.PositiveIntegerField(blank=True, null=True)),
                ('roteiros_revisados', models.PositiveIntegerField(blank=True, null=True)),
                ('cortes_pendentes', models.PositiveIntegerField(blank=True, null=True)),
                ('situacao_edicao', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linha de Edição',
                'verbose_name_plural': 'Cortes/Roteiros/Edição (linhas)',
                'indexes': [models.Index(fields=['curso', 'disciplina'], name='automacoes__curso_e885a6_idx')],
                'unique_together': {('serie', 'curso', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='GravacaoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, default='', max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('aulas_gravadas', models.PositiveIntegerField(blank=True, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('situacao_gravacao', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linha de Gravação',
                'verbose_name_plural': 'Gravação (linhas)',
                'indexes': [models.Index(fields=['curso', 'disciplina'], name='automacoes__curso_80ca88_idx')],
                'unique_together': {('serie', 'curso', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='MateriaisLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, default='', max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('produzidos', models.BooleanField(default=False)),
                ('formatados', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linha de Materiais',
                'verbose_name_plural': 'Materiais (linhas)',
                'indexes': [models.Index(fields=['curso', 'disciplina'], name='automacoes__curso_e3a679_idx')],
                'unique_together': {('serie', 'curso', 'disciplina')},
            },
        ),
    ]
